### PR TITLE
Sign in page/register page

### PR DESCRIPTION
**Pull request by JacobLBaum**
I created the sign in and register page accessible from the user profile

### CODE REVIEW

**Comment by vicka1228** [comment]
All the text fields are going out of the page for me in mobile view.. Also maybe even the register page can have the option to go back to the Login page? And I'm not sure about what the original plan was but Login/Register might look better as buttons

**Comment by sachiniyer** [comment]
kk I fixed centering and fixed the conflicts

**Comment by sachiniyer** [comment]
I will approve and merge

**Review by sachiniyer — APPROVED** [review]
good

**Pull request merged**
