### PR TITLE
200/fix test codes

### PR DESCRIPTION
**Pull request by minwukim**
What I did:
1. removed the test codes for post request and delete request of the User router (got complicated after JWT was involved)
2. removed the test codes for post request and delete request of the Post router (got complicated after Multer file upload was involved)
3. put all the test codes into the single file 'fullTest.js' (Not sure why, probably because of the async problem, the test codes work well if it is in the single file but never work if it is in the separate files)

Remarks:
-  I left all of the 4 original 4 files where we wrote the test codes. However, we should probably remove original 4 files before we submit.

### CODE REVIEW

**Comment by tasnimahmed11** [comment]
Do we still need this test or router? "GET specific user (GET request to users/:userId route)"

**Comment by vicka1228** [comment]
Out tests were supposed to work for the sprint 2 code so I'm not sure if we should be deleting any because of the JWT. Maybe we can ask if they even matter at this point?

**Comment by minwukim** [comment]
> 

I think we should. They are not working anymore because the router has changed. Now it requires the JWT authentication. We should either update it or remove it.

**Comment by vicka1228** [comment]
> Do we still need this test or router? "GET specific user (GET request to users/:userId route)"

I don't think we have a functionality for searching for users so maybe not?

**Comment by minwukim** [comment]
> Do we still need this test or router? "GET specific user (GET request to users/:userId route)"

I think we dont need that but lets just leave it there.
we need that for our code coverage requirement 😂

**Pull request merged**
